version: "3"
services:
  githost:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com/'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
        reservations:
          cpus: "2.0"
          memory: 4096M
    networks:
      - local

  jenkins:
    image: 'jenkins/jenkins:latest'
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
        reservations:
          cpus: "2.0"
          memory: 1024M
    networks:
      - local
  
networks:
  local:
    driver: bridge
